#!/bin/sh
set -e

OUTFILE="html_content.cpp"

to_compressed_c_array() {
	INFILE=$1
	varname=`echo "$INFILE" | tr '. ' '_'`

	echo "const PROGMEM char content_$varname[] = {"
	gzip -9 < "$INFILE" | xxd -i
	echo "};"
	echo "const size_t content_len_$varname = sizeof(content_$varname);"
}

# TODO: minimize HTML/JS/CSS
{
	cat << ENDCODE
/****************************************************************************
 *** Auto generated by gen_html_content.sh
 ****************************************************************************/
#include "html_content.h"

ENDCODE
	to_compressed_c_array "index.html"
	echo
	to_compressed_c_array "tzinfo.json"
} > "$OUTFILE"
